src/RootTesting.jl

Hello,
I would like to contribute a small testing module. It consists of fifteen testing functions in the paper by Alefeld, Potra and Shi. With different parameter values, it's 154 functions in total.
As written, it's not meant to be exported as a public interface, just used for testing and reference. It is helpful to have lots of interesting functions to compare different methods.
When I ran it, I got the following results:
MethodResults(fzero, evalcount=9378, numfailures=0, maxresidual=1.9220736113823023e-15)
MethodResults(fzero(x0), evalcount=7084, numfailures=83, maxresidual=6.356026815979021e-15)
MethodResults(fzero(x0,b), evalcount=11661, numfailures=0, maxresidual=1.9220736113823023e-15)
MethodResults(fzero/1, evalcount=5047, numfailures=90, maxresidual=59604.44477539063) …

Add testing functions from Alefeld-Potra-Shi

---

src/Roots.jl
src/SOLVE.jl
src/derivative_free.jl
src/fzero.jl
src/newton.jl

Using throw resets exception backtraces, making them less useful.

Use rethrow to preserve useful backtraces

---

.travis.yml

Julia v0.5 is the release, so this package clearly should be tested on it.

Enable testing on release

---

README.md
REQUIRE
src/Polys/real_roots.jl
src/Roots.jl
test/tests_multroot.jl

This removes the naive code for polynomial factors over Z or Q and uses the PolynomialFactor package instead. This closes issues #40.

use PolynomialFactors when finding real_roots over Z[x], Q[x]; close #40

---

test/test_derivative_free.jl
test/test_find_zero.jl
test/test_fzero.jl
test/test_newton.jl

replaces (at)test_approx_eq with \approx[tab], as possible.

v0.6 fix to test_approx deprecation

---

src/bracketing.jl
test/test_fzero.jl

``secant()`` previously chose a guess of ``NaN`` if the function took on
infinite values.  It now chooses ``(a+b)/2``.
This problem did not arise on the code path for ``Float64`` calculations, so it
remained hidden.

fix another NaN problem in bracketing

---

src/bracketing.jl

If signs don't change at the bounds, throw an ``ArgumentError`` instance with the error message. Otherwise it's hard to catch the error (and if you do, you still get warning messages).

Instantiate ArgumentError before throwing it

---

src/bracketing.jl
src/derivative_free.jl
src/find_zero.jl
test/test_find_zero.jl

This fixes a bug in calling `find_zero` with a Bisection method when `x0` is a scalar. This is now disallowed.

Adjust interface of find_zero

---

src/bracketing.jl
test/REQUIRE
test/runtests.jl
test/test_fzero.jl

Make sure bisection works if the root is on the boundary of the interval. I also added an appropriate test

Fix Inf handling in bisection64

---

src/Roots.jl
src/bracketing.jl
src/derivative_free.jl
src/find_zero.jl
src/newton.jl
test/test_find_zero.jl

Closes #80 
This implements 12 variants of the false position method, as discussed in Galdino. For many functions these give a bracketed zero-finding algorithm taking many fewer function calls than bisection, though some will take more function calls. The interface is through `find_roots`, as in `find_roots(sin, [3, 4], FalsePosition())`. The different variants are accessed by number (`FalsePosition(4)`, say) or by one of three names (e.g, `FalsePosition(:illinois)`.) Some documentation is found through `?FalsePosition`.

False position

---

src/bracketing.jl

almost_equal should use the type of its arguments, not Float64

---

src/derivative_free.jl

This attempts to give some reasonable approach when the guarded secant step fails due to the two x values agreeing. Hopefully addresses issue #88 . @ikirill is it possible to try your example with this fix?
(Basically, when the algorithm encounters two successive points that are the same, it moves to a different algorithm. I'm not certain that is the best solution, but it might prove more useful than what is currently the case.)

address issues with guarded secant step when two points are same. Fix #88 ?

---

src/bracketing.jl

I made a mistake in the a42 pull request: there is one place where it would incorrectly evaluate the function at a point before checking if the point is valid.
Test case:
```
function test_ipzero()
let (r, a, θ) = (1.0, -1.0, 0.01)
@test_nowarn Roots.a42(e -> e*e+r/a*sin(θ)*sqrt(muladd(e,e,-1))+r/a*(1-cos(θ))-1, 1+1e-8, 10.0)
end
end
```

Fix ipzero would evaluate the function at an invalid point.

---

README.md
src/bracketing.jl

* the use of `reinterpret` causes `bisection64` to allocate. This minor reworking cuts down on the number of `reinterpret` calls and reduces allocations a bit.

rework bisection64 to minimize allocations

---

.travis.yml
src/bracketing.jl

replace `realmin` with `floatmin` to fix 0.7 depwarn

fixed 0.7 depwarn

---

NEWS.md
README.md
src/derivative_free.jl
src/find_zero.jl
src/fzero.jl
test/test_fzero.jl

This package has `find_zero` and `fzero` as alternate interfaces for historic reasons. Rather than deprecate the latter, this PR takes advantage of the two names. There can be performance differences due to function specialization or not. If there is specialization, the first time a function is used there will be additional compilation which can be amortized over subsequent uses of the function. If there is no specialization the first time a function is used may be faster, but subsequent uses slower. Either may be desirable. This PR allows both, with `find_zero` specializing on the function call and `fzero` not specializing (similarly for `find_zeros` and `fzeros`.
```
julia> @btime find_zero(sin, 3.0, Order1())
329.372 ns (4 allocations: 320 bytes)
3.141592653589793
julia> @btime …
```

Differentiate find_zero and fzero

---

src/bracketing.jl
test/test_find_zero.jl

Issue #159 is about bracketing when an endpoint is a zero. Either this should be an error (a bracket isn't actually specified) or the zero should be returned. This chooses the user friendly latter for AbstractBisection.

close issue #159

---

src/bracketing.jl

This uses code from @greimel to add an entry point for bracketing when endpoints are  expensive to compute.

close  #156

---

Project.toml
src/bracketing.jl
src/derivative_free.jl
src/find_zero.jl
src/newton.jl
test/test_bracketing.jl
test/test_find_zero.jl

Introduces `find_bracket` to return a tuple containing a zero, an enclosing bracket, and a flat indicating if the value is an exact zero.
To do so, required adding a field in the struct to store the approximate zero instead of reusing `xn1`, which contains one part of the bracket.

rework to save bracket 

---

src/utils.jl
test/test_find_zero.jl

Hello and thank you for this great library.
There is a small bug in the _fbracket_ratio method. The return variable did not match what the documentation above it said:
`## use f[a,b] * f[a,c] / f[b,c]`
....
`out = (x2 * x3) / x3`

use the correct brackets in _fbracket_ratio

---

src/simple.jl
test/test_simple.jl

Please have a careful look, I'm by no means expert in numerical computation.
A few questions here as well:
* should we automatically switch to complex arithmetic, or throw an error asking the user to do so?
* please advise on `rtol` and `atol`. I just copied these from `newton` method (is there a reason to use rational exponents?? these divisions take longer than the root finding itself ;-)
* since this is a generalized secant method, it may substitute it when three values are available. It seems that one of such places is `bracketing.jl` but I don't feel competent enough

add simple muller method

---

src/bracketing.jl
src/derivative_free.jl

Hello,
found two variables that are declared but never used in their respective functions. Therefore I would assume it is safe to remove them?
The jit-compiler probably already removes them before compiling, so it should not impact performance, just make the code a little cleaner.

Remove two unused variables in bracketing.jl

---

src/Roots.jl
src/find_zero.jl
test/test_find_zero.jl

Issue 196 was about some interface to get NaN in place of an error.
This goes about it with a slightly different interface, following that of DifferentialEquations.
```
P = Roots.ZeroProblem(Order1(), sin, 3)
find_zero!(P)
```
Don't really like the name `ZeroProblem` for the type, so it isn't exported yet.

add ZeroProblem interface; close #196

---

Project.toml

There was a new release of SpecialFunctions.jl and this packages holds back updates of some other packages downstream. I've made a PR adding CompatHelper to automate this process in the future, cf. #202.

bump compat for SpecialFunctions

---

src/derivative_free.jl

`eltype(x1)[]` is incorrectly used here instead of `typeof(x1)[]`. Does not create a problem for most cases since `eltype(x) == typeof(x)` when `x` is a scalar.

fix typing of UnivariateZeroState init

---

.github/workflows/ci-nightly.yml
Project.toml
src/Roots.jl
src/bracketing.jl
src/find_zero.jl
src/utils.jl
test/test_find_zero.jl
test/test_simple.jl

* Use `solve`, `init` and `solve!` from CommonSolve for the iterator interface available with `ZeroProblem`.
* update tests to avoid warnings on function name reuse

Common solve

---

src/simple.jl

eliminated unnecessary function evals in muller

---

Project.toml
README.md
docs/src/roots.md
src/bracketing.jl
src/find_zero.jl
src/find_zeros.jl
src/utils.jl
test/runtests.jl
test/test_find_zero.jl
test/test_find_zeros.jl

Allow even more flexible interval specification for bracketing methods and `find_zeros`.

allow more flexible interval specification

---

Project.toml
src/simple.jl
test/test_newton.jl

When I switched from `Newton` to the simpler `newton`, my error handling no longer worked as I had anticpated a `Roots.ConvergenceFailed` error in this case (for package ActuaryUtilies.jl).

throw a typed error to allow for better handling

---

src/find_zero.jl
src/simple.jl
test/test_derivative_free_interactive.jl
test/test_find_zero.jl

This helps the compiler (see e.g. https://docs.julialang.org/en/v1/manual/performance-tips/#Checking-for-equality-with-a-singleton-1 and https://github.com/JuliaLang/julia/pull/36444).

Use `===` and `!==` for comparisons with `nothing`

---

src/bracketing.jl
src/find_zeros.jl
src/utils.jl
test/runtests.jl
test/test_bracketing.jl
test/test_find_zero.jl

Currently, the example in the README can't be inferred:
```julia
julia> using Roots
julia> f(x) = exp(x) - x^4;
julia> α₀,α₁,α₂ = -0.8155534188089607, 1.4296118247255556, 8.6131694564414;
julia> @code_warntype find_zero(f, (8,9), Bisection())
Variables
#self#::Core.Const(Roots.find_zero)
fs::Core.Const(f)
x0::Tuple{Int64, Int64}
method::Core.Const(Bisection())
Body::Any
1 ─ %1 = Roots.NullTracks()::Core.Const(Roots.NullTracks())
│   %2 = Core.NamedTuple()::Core.Const(NamedTuple())
│   %3 = Base.pairs(%2)::Core.Const(Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}())
│   %4 = Roots.:(var"#find_zero#23")(Roots.nothing, %1, false, %3, #self#, fs, x0, method)::Any
└──      return %4
```
The PR fixes this issue, also for brackets with mixed types (`Base.extrema` and …

Fix type inference of `Bisection` method

---

src/bracketing.jl
src/derivative_free.jl
src/find_zero.jl
src/non_simple.jl
test/REQUIRE

Removes some static parameters that are not needed (https://docs.julialang.org/en/v1/manual/style-guide/#Don't-use-unnecessary-static-parameters).

Remove unnecessary static parameters

---

Project.toml
src/find_zero.jl

This just makes a default `Tracks()` call be `Tracks(Float64, Float64)`.  This is a bit easier for the user to access this detail, which is in general available through `verbose=true`, but that doesn't work well with `Pluto`.

make default Tracks call

---

Project.toml
src/find_zero.jl
test/test_find_zero.jl

Make `Base.Broadcastable(::ZeroProblem)` be a reference to avoid broadcasting over non-iterable ZeroProblem instances

Base.broadcastable for ZeroProblem

---

Project.toml
docs/src/reference.md
src/bracketing.jl
test/test_allocations.jl
test/test_bracketing.jl

cf [discourse](https://discourse.julialang.org/t/julia-implementation-of-the-interpolate-truncate-project-itp-root-finding-algorithm/77739)
To match Wikipedia's example:
```
julia> solve(ZeroProblem(x -> x^3 - x - 2, (1,2)), 
Roots.ITP(κ₁=0.1, κ₂=2, n₀=1), 
xatol=1e-5, xrtol=0.0, 
verbose=true)
Results of univariate zero finding:
* Converged to: 1.5213830127326777
* Algorithm: Roots.ITP{Float64, Int64}(0.1, 2, 1)
* iterations: 6
* function evaluations ≈ 7
* stopped as x_n ≈ x_{n-1} using atol=xatol, rtol=xrtol
Trace:
(a_0, b_0) = ( 0.0000000000000000,  2.0000000000000000)
(a_1, b_1) = ( 1.0000000000000000,  2.0000000000000000)
(a_2, b_2) = ( 1.4333333333333333,  2.0000000000000000)
(a_3, b_3) = ( 1.4333333333333333,  1.5271314505696607)
(a_4, b_4) = ( 1.5200928115097818, …
```

add ITP bracketing method

---

Project.toml
src/find_zero.jl

This PR serves to increment the version number, effectively giving me contributor credit for making documentation improvements to `Tracker`. It also makes a reference to `Tracker` in the docstring for `find_zero`, as there now is a section for tracking in the documentation.

Increment version, make ref to `Tracker`

---

src/Bracketing/bisection.jl
test/test_bracketing.jl

add back `Roots.BisectionExact` as it is more performant than `Bisection` with 0 tolerances over FloatNN types.

add back bisection exact

---

src/trace.jl

Tweak format string to better handle x close to 0 or x far from 0.

use different format string for printing values

---

src/Bracketing/bisection.jl
src/convergence.jl

It is more performant to have a special path for the default Bisection. This moves that path from just a convergence check to a method for `solve!`, as it gains a bit more.

special case bisection

---

docs/src/index.md
docs/src/reference.md
docs/src/roots.md
src/Bracketing/bisection.jl
src/Bracketing/false_position.jl
src/Roots.jl
src/abstract_types.jl
src/convergence.jl
src/find_zero.jl
src/hybrid.jl
src/utils.jl

* use `maxiters` over `maxevals` (it is more standard) but allow `maxevals` if specified.
* clean up some docstrings

minor edits, tweaks

---

Project.toml
docs/src/index.md
src/Bracketing/bisection.jl
src/find_zero.jl
src/trace.jl

In issue #314 it was pointed out that `ForwardDiff` + `Bisection` has issues. This PR changes the default behavior for `find_zero(f, (a,b))` to use either `Bisection` or `A42` depending on the type of  `(a,b)` (as it always had been). This is breaking, but treated as a bug fix as v2.0.0 broke the code in Bijectors.
It also adds a (poorly named) method `find_zerov` to return the `Tracks` object in place of the solution and updates the doc string for `find_zero`.

rework default bracketing method; add find_zerov

---

Project.toml

Hello - I'm getting a transitive package limitation via this package with  Setfield. Can this be bumped? 
It's basically the same: https://github.com/jw3126/Setfield.jl/compare/v0.8.2...v1.0.0

Bump Setfield Compat to 1

---

src/chain_rules.jl

This PR improves the ChainRules definitions. It fixes some issues with the frule definition and simplifies the frule and rrule definitions by removing unnecessary functions (and hence the amount of boxed values) and more precomputations outside of the pullback.
Still needs tests with ChainRulesTestUtils to ensure that rrule and frule are implemented correctly. I assume some type inference checks might still fail due to closures.

Improve ChainRules definitions

---

Project.toml
src/chain_rules.jl
test/test_chain_rules.jl

As I assumed, unfortunately currently type inference checks fail. I haven't checked in detail what the underlying issue is. The tests with ChainRulesTestUtils show at least that otherwise the CR interface is implemented correctly.

Add tests with ChainRulesTestUtils

---

src/find_zeros.jl
test/test_find_zeros.jl

Throw earlier error when initial interval can't be narrowed.

earlier error when no initial interval is found. Close #339

---

Project.toml
docs/src/reference.md
docs/src/roots.md
ext/RootsIntervalRootFindingExt.jl
src/Bracketing/alefeld_potra_shi.jl
src/Derivative/halley_like.jl
src/find_zeros.jl
test/runtests.jl

* clean up docs slightly
* added `BracketedSchroder` as an alternative for the bracketing methods, useful for non-simple zeros
* Added extension for `IntervalRootFinding` overriding `find_zeros` when the interval is passed using an `IntervalRootFinding.Interval`.

clean up docs; BracketedSchroder; IntervalRoots extension

---

src/Derivative/halley_like.jl
src/Derivative/newton.jl

I don't see a reason to link via `tinyurl` instead directly to Wikipedia.
If I'm missing something, feel free to close that PR.

Use direct links instead of `tinyurl`

---

src/Derivative/lith.jl
test/test_newton.jl

solves #377
on the specifics:
i removed `evalf(F,x,i)` in favor of just `evalf(F,x)`. i checked that the same amount of calls, but a review would help. i noted some allocations, (`lmm(Val(i),...)` in a loop) but haven't fixed those. 
on the preferences, i used in some parts `only_f(F,x) = evalf(F,x,1)`, but those only appear in methods of D = 0. the consecuence for that is that you could pass a higher order tuple function into a Lith method and it could work, but those cases could be replaced by just using `F(x)` instead.

Lith patch

---

test/test_chain_rules.jl

ideally, this should be fixing by annotating  the `frule` and `rrule`, but this seems in line with the current strategy on that particular file, and that error is a bug in the ChainRules test suite

try to make the test pass on Nightly

---

src/find_zero.jl

The rest of the text seems to refer to `p` as the collection of parameters, but the function signature uses `p′`

Change p′ to p in `find_zero`'s docstring

---

Project.toml
src/Roots.jl

The docstring for the Roots module in https://github.com/JuliaMath/Roots.jl/blob/2e7c255e859a88238e5f858f180c8623babe2921/src/Roots.jl#L1-L8 and the docstring for the Roots module generated from the README in https://github.com/JuliaMath/Roots.jl/blob/2e7c255e859a88238e5f858f180c8623babe2921/src/Roots.jl#L79-L87 are conflicting and cause warnings (see, e.g., https://github.com/JuliaMath/Roots.jl/actions/runs/6356909458/job/17267239777#step:6:238):
```julia
1 dependency had warnings during precompilation:
┌ Roots [f2b01f46-fcfa-551c-844a-d8ac1e96c665]
│  ┌ Warning: Replacing docs for `Roots.Roots :: Union{}` in module `Roots`
│  └ @ Base.Docs docs/Docs.jl:243
└
```
They also don't work as intended:
```julia
julia> using Roots
help?> Roots
search: Roots promote_shape promote promote_type …
```

Fix docstring for Roots module

---

.gitignore
Project.toml
ext/RootsForwardDiffExt.jl
src/chain_rules.jl
test/test_chain_rules.jl
test/test_extensions.jl
tmp/Project.toml

Allow AD when Functor used
* Working with Zygote.gradient, Zygote.hessian
* Functors don't work with ForwardDiff
* ForwardDiff extension messes up Zygote.hessian for Functors
Close #384; Close #408

WIP: Issue 408

---

README.md
src/convergence.jl
src/find_zeros.jl
test/test_bracketing.jl
test/test_composable.jl

* Close issue #454
* Some check on runaway zeros due to reltol. Likely needs to be tweaked.

close #454; some guard on runaway roots

---

src/Bracketing/alefeld_potra_shi.jl
src/convergence.jl
test/test_composable.jl

...in the `AlefieldPotraShi` solver.
I ran into these constants causing a type promotion from `Float32` to `Float64` in a code I'm writing. Changing these locally avoids the error for me.
Unfortunately, I don't have an easy/isolated reproducer which can be turned into a test case — until the error arose, I had assumed a non-bracketing method was being used because I only provide an initial guess, so the implementation must get here on its own.

Avoid type promotions due to hard-coded tolerances

---

Project.toml
ext/RootsChainRulesCoreExt.jl
src/Roots.jl

The PR makes ChainRulesCore a weak dependency, most importantly to fix https://github.com/JuliaStats/Distributions.jl/pull/1900#issuecomment-2347904231 and similar cases in downstream packages that would like to keep their (possibly large) chunk of ChainRules definitions in an extension but currently therefore can't depend on Roots (since it would pull in ChainRulesCore which invalidates the use of an extension in the downstream package and since Pkg is not happy with the circular loading dependency it creates).

Make ChainRulesCore a weak dependency

---

Project.toml
src/Bracketing/alefeld_potra_shi.jl
src/Bracketing/bracketing.jl
src/Bracketing/itp.jl
src/convergence.jl
test/test_allocations.jl

* Issue 446 pointed out a type instability which is traced back to a dynamic dispatch in `init_options`. 
* this adds some specific choices

close #446; address type instability in init_options

---

src/Bracketing/itp.jl

The PR fixes two typos in the docstring of `ITP`.

Fix typos in the docstring of `ITP`

---

Project.toml
src/Bracketing/alefeld_potra_shi.jl
test/test_composable.jl

When using with `Measurements`, the Alefeld-Potra-Shi algorithms can lose their bracket, causing the algorithm to fail. This catches that behaviour and moves to check convergence.

fix issue with measurements; close #453

---

Project.toml
src/Bracketing/alefeld_potra_shi.jl
src/convergence.jl
test/test_find_zero.jl

Add an `assess_convergence` method for bisection that does not check `isinf_f`.
Update docs on Alefeld Potra methods about not honoring tolerances on size of f.
Close #457, Close #458

add separate assess method; add docs on AlefeldPotra methods

---

Project.toml
src/Bracketing/alefeld_potra_shi.jl

This adds a warning when `atol` or `rtol` are specified to Alefeld Potra Shi methods.
Still need to review if this can be done where other options are not considered.

add warning for certain tolerance specification; Close #479
