JuliaMath/Roots.jl

- src/newton.jl
Newton method can be used to obtain complex roots from a nonlinear function f(x)=0.
[+] Added a second method for `newtonmeth(f, fp, x0::Complex; kwargs... )`. Since there are now two methods:
- If x0 is Real, the routine will try to get a real root
- If x0 is Complex, the routine will obtain a complex root.
[+] I needed to add a second type ` ZeroFunctionComp`, similar to `ZeroFunction3` but with `x::Vector{Complex}` and `fxn::Complex`. This type is used in the second version of `newtonmeth`. I didn't found a smarter way to write this :) 
I obtained a very nice Julia set (Newton fractal) with this :)
> Newton method for complex roots

- .travis.yml
I flipped the switch to enable this, can shut it off if there's any reason it isn't wanted.
> enable travis ci

- .travis.yml
> replace release with 0.3 in .travis.yml

- REQUIRE
- src/Roots.jl
Ref #43. Seems like Docile is now redundant.
> Remove Docile from package

- appveyor.yml
> Add v0.5 testing to AppVeyor

- src/bracketing.jl
- src/find_zero.jl
> change error message when a bracket is expected and not given

- src/derivative_free.jl
minor adjustment to ensure same types are computed at outset.
> promote secant method

- .travis.yml
- appveyor.yml
> allow nightly to fail

- src/bracketing.jl
- src/derivative_free.jl
- src/newton.jl
update docs for find_zero algorithms, widen bisection _middle approach to Float 64, 32, and 16
> Method doc

- src/bracketing.jl
- test/RootTesting.jl
(fixes #93)
Evaluation count before:
```
julia> @printf "%s\n" run_tests((f,b) -> Roots.a42(f, b...), name="a42")
MethodResults(a42, evalcount=28745, numfailures=0, maxresidual=1.5630129569094153e-15)
```
After:
```
julia> @printf "%s\n" run_tests((f,b) -> Roots.a42(f, b...), name="a42")
MethodResults(a42, evalcount=3425, numfailures=0, maxresidual=1.5630129569094153e-15)
```
> Fix Alefeld-Potra-Shi to cache function values properly.

- src/find_zero.jl
adds a few conversions `float` calls
> close #105 issue with Symengine

- src/find_zero.jl
> fix bug with rtol clobbering atol

- src/bracketing.jl
* minor tweaks to get a42 to work with unitful
> fix a42 to work with Unitful correctly

- src/bracketing.jl
need to clean up _middle calls later
> oops, missed this

- NEWS.md
- REQUIRE
- src/Roots.jl
- src/bracketing.jl
- src/simple.jl
Moves things around in bisect to avoid two conditional checks within the main loop
> refactor bisect to limit conditionals

- src/bracketing.jl
- src/simple.jl
combine two related bisection methods.
> consolidate

- NEWS.md
- src/find_zeros.jl
- test/test_find_zeros.jl
* fix bug in find_zeros preventing it from working with Float32 values
> Find zeros eltype

- src/bracketing.jl
- src/derivative_free.jl
- src/find_zero.jl
- src/find_zeros.jl
- src/utils.jl
- test/RootTesting.jl
- test/test_composable.jl
- test/test_find_zero.jl
- test/test_fzero.jl
Adds methods Order1B, Order2B (King and Esser), analogs of Schroder's method for problems with multiple roots. Adjusts Order2 method to use secant step under certain circumstances.
> Add esser/king method

- src/find_zero.jl
- src/newton.jl
- test/test_find_zero.jl
* adds AbstractNewton method
* minor adjustment to default `xatol` value
* some documentation fixes
> abstract newton; aliases for Schroder; xatol default change

- src/bracketing.jl
- src/derivative_free.jl
* fix misnamed variable in bracketing method
* add some notes, fix some messages
> Bracket fix

- .gitignore
- Project.toml
> add Project.toml

- .travis.yml
- Project.toml
- appveyor.yml
- src/bracketing.jl
Find issue with find_bracket where xstar not in bracket.
> more work on 173 with AlefeldPotraShi

- src/fzero.jl
- test/test_find_zero.jl
> close issue #178

- Project.toml
- README.md
- src/bracketing.jl
- test/test_find_zero.jl
> Close issue #188

- .travis.yml
- Project.toml
- src/find_zeros.jl
* Bump version
* trim out some versions in testing
* add comment about IntervalRootFinding to documentation for find_zeros
> add comment in IntervalRootFinding, bump version, trim tested versions

- .github/workflows/ci-nightly.yml
- src/find_zero.jl
- src/utils.jl
Remove a `x^(1//3)` call, which is likely slow and not necessary, replace with `cbrt`.
> Rm rational exponent

- src/find_zero.jl
Before this change:
After this change:
> Fix the docs rendering was not correct

- docs/src/roots.md
- src/find_zero.jl
> clean up doc strings

- Project.toml
- docs/src/index.md
- docs/src/roots.md
- src/find_zero.jl
- src/fzero.jl
- src/lith.jl
- src/utils.jl
* minor doc edits
* bump version with @devmotion's PRs
> version bump; copy edits

- Project.toml
- src/newton.jl
- test/test_newton.jl
Change-Id: Iba18245615a1dcae533f691967082a6cbfebd426
> quadratic inverse, super halley and chebyshev like methods

- Project.toml
- docs/src/reference.md
* update docs after #248 
* version bump
> update docs; bump version

- .JuliaFormatter.toml
- .github/workflows/format-pr.yml
- Project.toml
- docs/src/reference.md
- src/Roots.jl
- src/bracketing.jl
- src/derivative_free.jl
- src/find_zero.jl
- src/find_zeros.jl
- src/fzero.jl
- src/lith.jl
- src/newton.jl
- src/non_simple.jl
- src/order0.jl
- src/simple.jl
- src/utils.jl
- test/runbenchmarks.jl
- test/runtests.jl
- test/test_allocations.jl
- test/test_bracketing.jl
- test/test_composable.jl
- test/test_derivative_free.jl
- test/test_derivative_free_interactive.jl
- test/test_find_zero.jl
- test/test_find_zeros.jl
- test/test_fzero.jl
- test/test_newton.jl
- test/test_simple.jl
* add JuliaFormatter to CI
* run JuliaFormatter on test/, src/
> Add JuliaFormatter to CI

- Project.toml
- src/find_zero.jl
- src/order0.jl
- test/test_find_zero.jl
* This adds a `solve!` method for `Order0`. There could be a better integration, but that is left for another day
* Add reference to docs for `solve!` in docs for `solve`.
> add solve for Order0, close #255

- Project.toml
- src/find_zero.jl
- src/order0.jl
* pushes hybrid methods down to `init` and not just with `find_zero`.
> more general fix for issue #255

- Project.toml
- src/bracketing.jl
- src/derivative_free.jl
- src/lith.jl
- src/newton.jl
- src/utils.jl
Fix issue when using SymPy expressions in place of functions by ensuring x values are type `T`
> add type annotations; issue with symbolic usage

- Project.toml
- src/find_zeros.jl
- test/test_find_zeros.jl
fix bug exposed by `find_zeros(x -> 4, -5, 5)`
> fix issue with integer-valued find_zeros

- Project.toml
- src/find_zero.jl
- src/find_zeros.jl
* use `io` in `show_trace` statement
* force `real` so `eps` call suceeds in `find_zeros`
> print fix, force real

- Project.toml
- src/bracketing.jl
- src/lith.jl
- test/test_bracketing.jl
- test/test_find_zero.jl
Add checks for fa*fb >= 0 in bracketing methods.
> close issue #264

- docs/src/reference.md
- src/bracketing.jl
- test/test_allocations.jl
- test/test_bracketing.jl
- test/test_find_zero.jl
This adds a `Ridder` method to the mix of accelerated bracketing methods.
> add Ridder method; close #281

- docs/src/reference.md
- docs/src/roots.md
- src/bracketing.jl
- test/test_bracketing.jl
With the addition of `ITP` and `Ridders` methods, it makes sense to complete the set of modern improvements listed at [Brent's](https://en.wikipedia.org/wiki/Brent%27s_method) method.
> Add Chandrapatlu algorithm

- src/Bracketing/bisection.jl
- src/Bracketing/false_position.jl
- test/test_bracketing.jl
> fix errors

- src/Bracketing/bracketing.jl
- src/Derivative/halley_like.jl
- src/Derivative/lith.jl
- src/Derivative/newton.jl
- src/Derivative/thukralb.jl
- src/abstract_types.jl
- src/trace.jl
* small edits to Bracketing
* Change Holley type to be a subtype of Newton type, not AbstractSecant
> bracketing edits; change halley <: newton

- src/Bracketing/alefeld_potra_shi.jl
- src/Bracketing/bisection.jl
- src/Bracketing/bracketing.jl
- src/Bracketing/brent.jl
- src/Bracketing/false_position.jl
- src/Derivative/lith.jl
- src/Derivative/thukralb.jl
- src/convergence.jl
- src/find_zero.jl
- test/test_bracketing.jl
- test/test_find_zero.jl
* centralizes assessment of convergence.
* allows removal of BisectionExact leaving Bisection with better performance
> Cleanup convergence

- src/convergence.jl
- src/trace.jl
> check for exact zero

- src/DerivativeFree/order0.jl
- src/Roots.jl
- src/hybrid.jl
* breakout hybrid
* fix logging issue when bracket is chosen
> break out hybrid from Order0; fix logging bug

- src/trace.jl
- src/utils.jl
* add a few generics (`last`, `get`, `empty!`) and update docs accordingly.
> Cleanup trace unicode

- .github/workflows/ci.yml
- test/test_find_zero.jl
* add v1.6.X in testing matrix
* allow v1.0.X to fail
> add test for v1.6; allow v1.0.X to fail

- README.md
- docs/make.jl
> Update document deployment

- Project.toml
- docs/src/roots.md
- src/Roots.jl
- src/chain_rules.jl
- src/find_zero.jl
- src/functions.jl
- src/hybrid.jl
- test/runtests.jl
- test/test_chain_rules.jl
* close #325 (hopefully implementation is correct)
* allow p to be passed as positional argument. (positional works better with broadcasting and with differentiation)
* update docs on differentiating
> add rrule frule; adjust how parameters are passed

- Project.toml
- src/trace.jl
- test/test_find_zero.jl
Adds `show_tracks` method for complex values tracks. By @AuroraDysis .
> merge in code of AuroraDysis to close printing issue [close #336]

- Project.toml
- src/Bracketing/alefeld_potra_shi.jl
- src/Bracketing/bisection.jl
- src/Bracketing/brent.jl
- src/Bracketing/chandrapatlu.jl
- src/Bracketing/false_position.jl
- src/Bracketing/itp.jl
- src/Bracketing/ridders.jl
- src/Derivative/newton.jl
- src/Derivative/thukralb.jl
- src/DerivativeFree/esser.jl
- src/DerivativeFree/king.jl
- src/DerivativeFree/order5.jl
- src/DerivativeFree/secant.jl
- src/DerivativeFree/steffensen.jl
- test/test_find_zero.jl
Close issue #343 by adding type declarations when there is a function call in `update_state`.
> add Type declarations with function calls

- NEWS.md
- docs/src/index.md
- src/Bracketing/bisection.jl
- src/Derivative/lith.jl
- src/Derivative/thukralb.jl
- src/abstract_types.jl
- src/alternative_interfaces.jl
- src/convergence.jl
- src/find_zero.jl
- src/simple.jl
- src/trace.jl
- src/utils.jl
- test/test_bracketing.jl
Corrects some typos in the repository.
> Correct some typos

- Project.toml
- docs/src/roots.md
- src/Bracketing/alefeld_potra_shi.jl
- src/convergence.jl
- src/find_zero.jl
- src/trace.jl
- test/test_find_zeros.jl
Alternative solution to #369 from #370 which should catch more cases where the initial step hits an asymptote.
> adjust for oo values; close #369

- docs/src/roots.md
- src/convergence.jl
- test/test_bracketing.jl
* Don't make another function call if unnecessary
* add test
> tweak to fix for #368

- src/simple.jl
- test/runtests.jl
- test/test_bracketing.jl
- test/test_derivative_free.jl
- test/test_find_zero.jl
This a fraction (~7/8) faster than Roots.A42 and more faithful to the original algorithm (though still off in evaluation counts). Might be of independent interest.
> add simple a42 method

- docs/src/geometry-zero-finding.md
Add some documentation on how to visualize one step of various algorithms.
> add documentation on visualizing one step

- src/Derivative/lith.jl
- test/test_allocations.jl
Hacky way to avoid allocations in LithBoonkkampIJzerman methods noticed in #377
> Lith allocate

- docs/src/roots.md
- ext/RootsForwardDiffExt.jl
> add comment about what is 1.9 (julia). Close issue #388

- Project.toml
- src/Bracketing/alefeld_potra_shi.jl
- src/Bracketing/bisection.jl
- src/Bracketing/bracketing.jl
- src/Bracketing/brent.jl
- src/Bracketing/chandrapatlu.jl
- src/Bracketing/itp.jl
- src/Derivative/halley_like.jl
- src/Derivative/newton.jl
- src/Derivative/thukralb.jl
- src/DerivativeFree/derivative_free.jl
- src/DerivativeFree/king.jl
> missing promotion

- docs/Project.toml
- docs/src/geometry-zero-finding.md
- docs/src/index.md
- docs/src/reference.md
- src/Bracketing/alefeld_potra_shi.jl
- src/DerivativeFree/esser.jl
- src/DerivativeFree/king.jl
- src/DerivativeFree/steffensen.jl
- src/Roots.jl
- src/alternative_interfaces.jl
- src/convergence.jl
- src/find_zero.jl
- src/simple.jl
- src/trace.jl
- src/utils.jl
* Documentation adjustments needed when bumping Documenter to `v1.0`.
> Documenter 1

- Project.toml
- src/convergence.jl
- src/hybrid.jl
- test/test_allocations.jl
Fix type instability introduced with untyped NaN value.
> Close Issue #423

- README.md
- Old build status is always failed:  https://github.com/JuliaMath/Roots.jl/workflows/CI/badge.svg
- Codecov Badge copy from: https://app.codecov.io/gh/JuliaMath/Roots.jl/settings/badge
> CI: Update ci badge

- Project.toml
- docs/src/index.md
- docs/src/reference.md
- src/DerivativeFree/sidi.jl
- src/Roots.jl
- src/find_zero.jl
- test/test_derivative_free.jl
- test/test_find_zero.jl
> implement Sidi methods
